select * from course;
select * from duration;
select * from kindvehicle;
select * from price;
select * from schedule;
select * from studentenrollment;
select * from studentenrollment_course;
select * from teacher;
select * from vehicle;